1.  User Input and String Formatting .  
Write a program that asks the user for their name and age. Display a 
message like: 
"Hi Anishl, you will be 25 in 5 years." 

In [1]:
# Asking the user for their name and age
name = input("What is your name? ")
age = int(input("How old are you? "))

# Calculate the age in 5 years
age_in_5_years = age + 5

# Display the formatted message
print(f"Hi {name}, you will be {age_in_5_years} in 5 years.")

Hi anish, you will be 27 in 5 years.


2.  Prime Number Checker .  
Write a function that checks if a number is prime. Let the user input a 
number and display whether it's prime or not. 

In [2]:
# Function to check if a number is prime
def is_prime(number):
    # Handle edge cases for numbers less than 2
    if number <= 1:
        return False
    # Check for divisibility from 2 up to the square root of the number
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            return False
    return True

# Ask the user for a number
user_input = int(input("Enter a number to check if it's prime: "))

# Check if the number is prime and display the result
if is_prime(user_input):
    print(f"{user_input} is a prime number.")
else:
    print(f"{user_input} is not a prime number.")


7 is a prime number.


3.  Loops Practice  
a) Print all even numbers from 1 to 50 using a loop.  
b) Write a function to calculate factorial of a given number using a while 
loop. 

In [3]:
# Loop to print even numbers from 1 to 50
for number in range(1, 51):
    if number % 2 == 0:
        print(number)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [5]:
# Function to calculate factorial using while loop
def factorial(n):
    result = 1
    while n > 1:
        result *= n
        n -= 1
    return result

# user input and calculation
num = int(input("Enter a number to calculate its factorial: "))
print(f"The factorial of {num} is {factorial(num)}.")


The factorial of 5 is 120.


4. List Operations  
o Create a list of integers.  
o Write a function that finds the maximum number.  
o Write another function that returns a list with the square of each 
number. 

In [13]:
# to create a list
my_list = [1, 100, 34, 23, 12, 11, 32]
my_list


[1, 100, 34, 23, 12, 11, 32]

In [15]:
# function to find max number in the list
def max_num(list):
    return max(list)

max_num(my_list)


100

In [17]:
# function that returns a list with square of each number
def square(list):
    return [num**2 for num in list]

square(my_list)

[1, 10000, 1156, 529, 144, 121, 1024]

## File handling in python
-Create a text file named sample.txt and write any 5 sentences into it.  
o Read the file and print its contents.  
o Count the total number of words and print the result.

In [1]:
## create and write 5 sentences to file named "sample.txt"
with open("sample.txt","w") as file:
    file.write("This is the first sentence.\n")
    file.write("This is the second sentence.\n")
    file.write("This is the third sentence.\n")
    file.write("This is the fourth sentence.\n")
    file.write("This is the fifth sentence.\n")


In [2]:
## read the file and print its contents
with open("sample.txt", "r") as file:
    content = file.read()
    print("The file contents are:\n")
    print(content)

The file contents are:

This is the first sentence.
This is the second sentence.
This is the third sentence.
This is the fourth sentence.
This is the fifth sentence.



In [3]:
## to count the total number of words and print it
words = content.split()  # split() without arguments splits the string on any whitespace (spaces, newlines, tabs) and returns a list
count = len(words)
print(f"The total number of words in the file is {count}")

The total number of words in the file is 25


## Basics with Numpy Arrays  
o Create a 1D array with numbers from 1 to 10.  
o Create a 2D array of shape (3, 4).  
o Slice both arrays and print selected elements. 

In [6]:
import numpy as np

# create a 1D array from number 1 to 10
array_1d = np.arange(1, 11)
print(f"1D array:",array_1d)

# create a 2D array of shape (3, 4)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print(f"2D array: ",array_2d)

# Slice the 1D array: elements from index 2 to 6 (inclusive of 2, exclusive of 7)
slice_1d = array_1d[2:7]
print("\nSliced 1D Array:")
print(slice_1d)

# Slice the 2D array: rows 0 and 1, columns 1 to 3
slice_2d = array_2d[0:2, 1:4]
print("\nSliced 2D Array:")
print(slice_2d)

1D array: [ 1  2  3  4  5  6  7  8  9 10]
2D array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sliced 1D Array:
[3 4 5 6 7]

Sliced 2D Array:
[[2 3]
 [5 6]]


## Array operations  
o Perform element-wise addition, subtraction, and multiplication on two arrays.  
o Find the mean, median, and standard deviation of an array. 

In [7]:

# Create arrays
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

# Element-wise operations
print("Add:", a + b)
print("Subtract:", a - b)
print("Multiply:", a * b)
print("Divide:", a / b)

# Statistics on array 'a'
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Std Dev:", np.std(a))


Add: [12 24 35 48]
Subtract: [ 8 16 25 32]
Multiply: [ 20  80 150 320]
Divide: [5. 5. 6. 5.]
Mean: 25.0
Median: 25.0
Std Dev: 11.180339887498949


# Data manipulation using pandas


## create a Dataframe  
Create a DataFrame using a dictionary with names and marks of 
students. Add columns for Math, Science, and English.

In [15]:
import pandas as pd

# Create a dictionary with student data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Math': [85, 70, 92, 88, 76],
    'Science': [90, 82, 88, 91, 80],
    'English': [87, 69, 85, 89, 83]
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)


      Name  Math  Science  English
0    Alice    85       90       87
1      Bob    70       82       69
2  Charlie    92       88       85
3    David    88       91       89
4      Eva    76       80       83


## Data Analysis  
• Display top 5 and bottom 5 rows.  
• Show data types and basic statistics.  
• Filter rows where average marks are more than 75.  
• Add a column called "Result" with values 'Pass' or 'Fail' based on average marks.

In [12]:
# display the top and bottom rows
print("Top 5 rows :\n", df.head())
print("----------------------------")
print("Bottom 5 rows:\n",df.tail())

Top 5 rows :
       Name  Math  Science  English
0    Alice    85       90       87
1      Bob    78       82       79
2  Charlie    92       88       85
3    David    88       91       89
4      Eva    76       80       83
----------------------------
Bottom 5 rows:
       Name  Math  Science  English
0    Alice    85       90       87
1      Bob    78       82       79
2  Charlie    92       88       85
3    David    88       91       89
4      Eva    76       80       83


In [ ]:

# Data types and basic statistics
print(" Data Types:\n", df.dtypes)
print("\n Basic Statistics:\n", df.describe())

 Data Types:
 Name       object
Math        int64
Science     int64
English     int64
dtype: object

 Basic Statistics:
             Math   Science    English
count   5.000000   5.00000   5.000000
mean   83.800000  86.20000  84.600000
std     6.723095   4.91935   3.847077
min    76.000000  80.00000  79.000000
25%    78.000000  82.00000  83.000000
50%    85.000000  88.00000  85.000000
75%    88.000000  90.00000  87.000000
max    92.000000  91.00000  89.000000


In [16]:
# filter rows where average marks > 75
df["average"] = df[["Math","Science","English"]].mean(axis=1)

high_scorers = df[df["average"]>75]
print("Filtered dataframe: \n", high_scorers)

Filtered dataframe: 
       Name  Math  Science  English    average
0    Alice    85       90       87  87.333333
2  Charlie    92       88       85  88.333333
3    David    88       91       89  89.333333
4      Eva    76       80       83  79.666667


In [18]:
# add column "Result"
df["Result"] = df["average"].apply(lambda x: "Pass" if x > 40 else "Fail")
df

Name  Math  Science  English    average Result
0    Alice    85       90       87  87.333333   Pass
1      Bob    70       82       69  73.666667   Pass
2  Charlie    92       88       85  88.333333   Pass
3    David    88       91       89  89.333333   Pass
4      Eva    76       80       83  79.666667   Pass

## Grouping and Aggregation  
Group the data by "Result" and calculate average marks for each subject.

In [19]:
grouped_average = df.groupby("Result")[["Math", "Science", "English"]].mean()
print(grouped_average)

        Math  Science  English
Result                        
Pass    82.2     86.2     82.6
