In [1]:
## loading the inbuilt iris dataset
from sklearn.datasets import load_iris
iris = load_iris()

# x is feature matrix and y is response/target vector

x = iris.data
y = iris.target

In [2]:
## get the features name and target name
features_name = iris.feature_names
target_name = iris.target_names

print(features_name)
print(target_name)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [ ]:
# type of features and target variables
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
# First 5 rows of feature matrix
print(iris.data[:5])

# first 5 rows of target vector
print(iris.target[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [8]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (80% train, 20% test)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Check the shapes
print("Training set shape:", x_train.shape)
print("Test set shape:", x_test.shape)

Training set shape: (120, 4)
Test set shape: (30, 4)
