In [1]:
# importing numpy
import numpy as np

### Creating arrays

In [3]:
# From a list
arr = np.array([1, 2, 3])
print(arr)

# 2D array (matrix)
mat = np.array([[1, 2], [3, 4]])
print(mat)

# Range of numbers
arr2 = np.arange(0, 10, 2)
print(arr2)

# Evenly spaced numbers (useful for plotting)
print(np.linspace(0, 1, 5))

# Zeros, ones, and random arrays
print(np.zeros((3, 3)))
print(np.ones((2, 2)))
print(np.random.rand(3, 3))      # Uniform distribution
print(np.random.randn(3, 3))     # Standard normal distribution
print(np.random.randint(0, 10, (3, 3)))  # Random integers


[1 2 3]
[[1 2]
 [3 4]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.99184607 0.82746445 0.87191584]
 [0.97402421 0.81959938 0.81061246]
 [0.44129595 0.2273024  0.3958601 ]]
[[-0.80370575 -1.77275242  1.28426601]
 [ 0.9715442   1.54636591  0.30133405]
 [-0.81370059 -0.45960382 -0.70047208]]
[[3 0 0]
 [7 6 5]
 [6 4 8]]


### Array operations

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print(a + b)
print(a * b)
print(a / b)
print(a ** 2)

# Broadcasting
print(a + 10)


[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[11 12 13]


## shape, reshape and dimensions

In [6]:
print(arr.shape)        # Dimensions
print(arr.reshape(1, 3))
transposed = arr.T           # Transpose
print(transposed.shape)
print(arr.ndim)         # Number of dimensions


(3,)
[[1 2 3]]
(3,)
1
